[project]
name = "PySqlitMCP"
version = "0.2.6"
description = "A database operation toolkit based on FastMCP framework and PySqlit library for complete SQLite database management"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.2",
    "pysqlit>=0.2.5",
]
